### ISSUE TITLE
version 3.1.1 Crash Caused by: java.lang.NoSuchFieldError: No static field xxx of type I in class Landroidx/core/R$id

### ISSUE THREAD

**Issue by senlsy** [segment-integrations/analytics-android-integration-amplitude#63]
![image](https://user-images.githubusercontent.com/7843921/174008404-49c7188a-7dd8-4494-87df-24eb4242266c.png)

The androidx code is packed into the aar package！！！
<img width="577" alt="image" src="https://user-images.githubusercontent.com/7843921/174008121-9fc6b467-8507-481d-9e20-417fab62adbb.png">

**Comment by maitolab** [comment]
I faced issues as well. The library should not embed android core into the library. I reverted to 3.1.0 to fix the problem. @senlsy

**Comment by senlsy** [comment]
> I faced issues as well. The library should not embed android core into the library. I reverted to 3.1.0 to fix the problem. @senlsy 

Yes, I alsed reverted to 3.1.0 to fix it.

**Comment by prayansh** [comment]
@ramprasad-vuclip @maitolab #61  was the only change we made for going from 3.1.0 to 3.1.1

Would u happen to know what change in the build.gradle could have potentially caused this?

**Comment by prayansh** [comment]
I have released [v3.1.2](https://github.com/segment-integrations/analytics-android-integration-amplitude/releases/tag/3.1.2) in order to fix this. 

Closing this issue. Please try it out and let us know if you are still facing the issue on this thread.
